version: '3.8'
services:
  mongodb_server:
    image: mongo:6.0
    container_name: acc-test-mongodb
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    logging:
      driver: none
    volumes:
      - ./docker/acc-test/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - acc-test-network

  api_server:
    container_name: acc-test-server
    build:
      context: .
      dockerfile: ./local-server.Dockerfile
    environment:
      PK_ENV: test
      MONGO_DB_URI: mongodb://tester:tester@mongodb_server:27017/
      MONGO_DB_NAME: testdb
      EMAIL_HOST: mail.email.com
      EMAIL_USER: test@email.com
      EMAIL_PASS: password
      JWT_SECRET: supersecretstring
      LOGIN_CODE_EXPIRY: 15
      TOKEN_EXPIRY: 7
      NOTIFICATION_EMAIL: main@test.com
      SELF_URL: https://pk-central.app
      TRIPZ_FRONTEND_URL: https://tripz.com
      START_FRONTEND_URL: https://start.com
      EMAILS_ALLOWED:
      MAILER_URL: https://stuff.p-kin.com/mock-mailer.php
      MAILER_API_KEY: mailerapikey123
      PROXY_AIRLABS_AIRLINES_URL: https://stuff.p-kin.com/mock-airlines.php
      PROXY_AIRLABS_AIRPORTS_URL: https://stuff.p-kin.com/mock-airports.php
      PROXY_LOCATION_REVERSE_URL: https://stuff.p-kin.com/mock-reverse.php
    ports:
      - "5678:5678"
    volumes:
      - app-data:/app
    working_dir: /app
    depends_on:
      - mongodb_server
    networks:
      - acc-test-network

  acc_test:
    container_name: acc-test-tester
    build:
      context: .
      dockerfile: ./acc-test.Dockerfile
    environment:
      TEST_API_URL: http://api_server:5678
    depends_on:
      - mongodb_server
      - api_server
    networks:
      - acc-test-network

volumes:
  app-data:
    name: acc-test-app-data

networks:
  acc-test-network:
    name: acc-test-network