### Get activities data for user
GET {{baseUrl}}/activities
Content-Type: application/json
Authorization: Bearer {{token}}

### Initialize activities data for user
POST {{baseUrl}}/activities/initialize
Content-Type: application/json
Authorization: Bearer {{token}}

### Update goals
PATCH {{baseUrl}}/activities/goals
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "walkWeeklyGoal": 30,
  "walkMonthlyGoal": 30,
  "cyclingWeeklyGoal": 30,
  "cyclingMonthlyGoal": 30
}

### Add new chore
POST {{baseUrl}}/activities/chore
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "kmInterval": 20,
  "lastKm": 1356,
  "name": "other chore"
}

### Update chore
PUT {{baseUrl}}/activities/chore/a91ab11c-629a-4a9f-bc27-cb6a0d16002d
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "kmInterval": 40,
  "lastKm": 1376,
  "name": "abcdef"
}

### Delete chore
DELETE {{baseUrl}}/activities/chore/6fb9cfcd-43c5-43ae-8da8-d04355f84c3a
Content-Type: application/json
Authorization: Bearer {{token}}
