### Get login code email
POST http://localhost:8888/auth/login
Content-Type: application/json

{
  "email": "kinpeter85@gmail.com"
}

### Verify login code
POST http://localhost:8888/auth/verify-code
Content-Type: application/json

{
  "email": "kinpeter85@gmail.com",
  "loginCode": "947749"
}

### Verify magic link
GET http://localhost:8888/auth/verify-link/{{token}}/dev

### Refresh token
POST http://localhost:8888/auth/token-refresh
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "kinpeter85@gmail.com"
}