### Get login code email
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "kinpeter85@gmail.com"
}

### Get instant login code DEV ENV ONLY!
POST {{baseUrl}}/auth/instant-login-code
Content-Type: application/json

{
  "email": "main@test.com"
}

### Verify login code
POST {{baseUrl}}/auth/verify-code
Content-Type: application/json

{
  "email": "main@test.com",
  "loginCode": "255944"
}

### Verify magic link
GET {{baseUrl}}/auth/verify-link/{{token}}/dev

### Refresh token
POST {{baseUrl}}/auth/token-refresh
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "kinpeter85@gmail.com"
}