### Get cycling data for user
GET {{baseUrl}}/cycling
Content-Type: application/json
Authorization: Bearer {{token}}

### Initialize cycling data for user
POST {{baseUrl}}/cycling/initialize
Content-Type: application/json
Authorization: Bearer {{token}}

### Update weekly goal
PATCH {{baseUrl}}/cycling/weekly-goal
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "weeklyGoal": 30
}

### Update monthly goal
PATCH {{baseUrl}}/cycling/monthly-goal
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "monthlyGoal": 300
}

### Add new chore
POST {{baseUrl}}/cycling/chore
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "kmInterval": 20,
  "lastKm": 1356,
  "name": "other chore"
}

### Update chore
PUT {{baseUrl}}/cycling/chore/a91ab11c-629a-4a9f-bc27-cb6a0d16002d
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "kmInterval": 40,
  "lastKm": 1376,
  "name": "abcdef"
}

### Delete chore
DELETE {{baseUrl}}/cycling/chore/6fb9cfcd-43c5-43ae-8da8-d04355f84c3a
Content-Type: application/json
Authorization: Bearer {{token}}
