### Get flights for user
GET {{baseUrl}}/flights
Content-Type: application/json
Authorization: Bearer {{token}}

### Add flight
POST {{baseUrl}}/flights
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date": "2025-03-08",
  "flightNumber": "BT20",
  "from": {
    "city": "Istanbul",
    "name": "Istanbul Airport",
    "iata": "IST",
    "icao": "LTFM",
    "lat": 41.2629,
    "lng": 28.74242,
    "country": "Turkey"
  },
  "to": {
    "city": "Seoul",
    "name": "Incheon",
    "iata": "ICN",
    "icao": "RKSI",
    "lat": 37.4492,
    "lng": 126.45095,
    "country": "Korea"
  },
  "departureTime": "17:10:00",
  "arrivalTime": "08:55:00",
  "duration": "09:45:00",
  "airline": {
    "name": "Turkish Airlines",
    "iata": "TK",
    "icao": "THY"
  },
  "aircraft": {
    "name": "Boeing 777-300ER",
    "icao": "B77W"
  },
  "registration": "TC-LJB",
  "seatNumber": "24H",
  "seatType": "Aisle",
  "flightClass": "Economy",
  "flightReason": "Leisure",
  "note": "",
  "distance": 7925,
  "isPlanned": true
}

### Update flight
PUT {{baseUrl}}/flights/17818a23-a264-4459-8696-3d4f87603fbd
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date": "2025-03-08",
  "flightNumber": "BT20",
  "from": {
    "city": "Istanbul",
    "name": "Istanbul Airport",
    "iata": "IST",
    "icao": "LTFM",
    "lat": 41.2629,
    "lng": 28.74242,
    "country": "Turkey"
  },
  "to": {
    "city": "Seoul",
    "name": "Incheon",
    "iata": "ICN",
    "icao": "RKSI",
    "lat": 37.4492,
    "lng": 126.45095,
    "country": "Korea"
  },
  "departureTime": "17:10:00",
  "arrivalTime": "08:55:00",
  "duration": "09:45:00",
  "airline": {
    "name": "Turkish Airlines",
    "iata": "TK",
    "icao": "THY"
  },
  "aircraft": {
    "name": "Boeing 777-300ER",
    "icao": "B77W"
  },
  "registration": "TC-LJB",
  "seatNumber": "24H",
  "seatType": "Aisle",
  "flightClass": "Economy",
  "flightReason": "Leisure",
  "note": "",
  "distance": 7925,
  "isPlanned": false
}

### Delete flight
DELETE {{baseUrl}}/flights/fdb0aa3a-d7c7-42a6-abef-c604a417ff05
Content-Type: application/json
Authorization: Bearer {{token}}

