### Get notes for user
GET {{baseUrl}}/notes
Content-Type: application/json
Authorization: Bearer {{token}}

### Add note
POST {{baseUrl}}/notes
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "only text",
  "archived": true,
  "pinned": false,
  "links": [
    {
      "name": "a link",
      "url": "https://google.com"
    }
  ]
}

### Update note
PUT {{baseUrl}}/notes/18b82f2b-b882-491a-9b76-6d057fe7eba9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "new note updated",
  "archived": false,
  "pinned": false,
  "links": [
    {
      "name": "a link",
      "url": "https://google.com"
    },
    {
      "name": "another link",
      "url": "https://yahoo.com"
    }
  ]
}

### Delete note
DELETE {{baseUrl}}/notes/a6c488d9-25c6-4f74-98d3-659b138a0426
Content-Type: application/json
Authorization: Bearer {{token}}

