### Get birthdays data for user
GET {{baseUrl}}/proxy/birthdays
Content-Type: application/json
Authorization: Bearer {{token}}

### Get korean data for user
GET {{baseUrl}}/proxy/korean
Content-Type: application/json
Authorization: Bearer {{token}}

### Get airport data by iata code
GET {{baseUrl}}/proxy/airport/tll
Content-Type: application/json
Authorization: Bearer {{token}}

### Get airline data by iata code
GET {{baseUrl}}/proxy/airline/bt
Content-Type: application/json
Authorization: Bearer {{token}}