### Get shortcuts for user
GET {{baseUrl}}/shortcuts
Content-Type: application/json
Authorization: Bearer {{token}}

### Add shortcut
POST {{baseUrl}}/shortcuts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://www.google.com",
  "iconUrl": "google.png",
  "name": "Google",
  "priority": 1,
  "category": "CODING"
}

### Update shortcut
PUT {{baseUrl}}/shortcuts/02dc5644-561c-41ce-84bf-0f44f813f2d2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "url": "https://www.google.com",
  "iconUrl": "google.png",
  "name": "Google",
  "priority": 10,
  "category": "CODING"
}

### Delete shortcut
DELETE {{baseUrl}}/shortcuts/02dc5644-561c-41ce-84bf-0f44f813f2d2
Content-Type: application/json
Authorization: Bearer {{token}}

