version: '3.7'
services:
  mongodb_server:
    image: mongo:6.0
    environment:
      MONGO_INITDB_DATABASE: central
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
