name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  ci:
    name: PK-Central CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.5.1'

      - name: Install dependencies
        run: npm ci

      - name: Run code checks and unit tests
        run: npm run checks

      - name: Run API acceptance tests in Docker
        run: docker compose -f ./acc-test.docker-compose.yml up --build --exit-code-from acc_test
